mk1micros/awsbuild

.github/workflows/terraform_build.yml
=> changes to workflow

terraform/modules/private_dns/main.tf, terraform/modules/private_dns/variables.tf, terraform/modules/private_dns/versions.tf
new dns module for private dns
=> new module

terraform/modules/private_dns/main.tf, terraform/modules/private_dns/variables.tf, terraform/privatedns.tf
=> route associastrion

terraform/modules/private_dns/main.tf
=> new resource

.github/ISSUE_TEMPLATE/test.yml, .github/workflows/trivy.yml, .github/workflows/updatereadme.yml
This updates the issues template
=> template changes

.github/workflows/trivy.yml
=> trivy changes

.github/workflows/trivy.yml
Adding back removed permissions
=> Added permissions to job

terraform/.terraform.lock.hcl, terraform/main.tf, terraform/modules/external_dns/main.tf, terraform/modules/external_dns/variables.tf, terraform/networks.tf, terraform/privatedns.tf, terraform/variables.tf
=> infastructure changes

.github/workflows/terraform_build.yml
=> flow logs updated

terraform/networks.tf, terraform/securityg.tf
to simplify the networking i have removed the vpc peering and the ireland VPC
=> remove Ireland region

.github/workflows/terraform_plan.yml
New way of doing terraform plan
=> new terraform plan test

.github/workflows/updatereadme.yml, terraform/main.tf
=> test new workflow

terraform/acm.tf, terraform/fargate.tf, terraform/main.tf
remove resources after 1 month test
=> cost saving

terraform/iam.tf
PR to test and create centerlised root access to all org accounts
=> centralised root access

terraform/iam.tf
=> code update v2

.github/workflows/create-newenv.yml
=> change to checkout and also to add debug

.github/workflows/create-newenv.yml
added extra bit to the commit section
=> change to commit section

.github/workflows/create-newenv.yml
=> commit changes

.github/workflows/create-newenv.yml
=> error correction

.github/ISSUE_TEMPLATE/new-environment.yml, .github/workflows/create-newenv.yml, scripts/amend-accounts.py
Changes to amend accounts and how the workflow executes
=> changes to workflow and template

.github/workflows/create-newenv.yml
Adds functionality to the new workflow by adding the PR as a comment on the logged issue
=> New functionality

.github/workflows/create-newenv.yml
Adds PR linking to the Issue request
=> Added linking of the PR to the issue on pr creation

.github/ISSUE_TEMPLATE/new-environment.yml, .github/ISSUE_TEMPLATE/test.yml, .github/workflows/create-newenv.yml
Removing debuging code from workflow
=> code clean un
